version: "3"

services:
  web:
    build: .
    env_file:
      - ./env/postgres.env
    command: python3 /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - 8000:8000
  rindus_db:
    env_file:
      - ./env/postgres.env
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: -p 5433
volumes:
  postgres: